title: Thitipattra Buabanprom  # You can add your name here

# logo: my-profile.png # Use a relative path to logo image 

description: A static website driven by Jekyll 

show_downloads: true # Fix spelling

theme: jekyll-theme-midnight 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: thitipattra.22bow@gmail.com # 
